---
- hosts: localhost
  gather_facts: yes

  environment:
    AWS_DEFAULT_REGION: "us-east-1"

  vars:
    manifest_file: /tmp/amazon_cloud_manifest.yaml
  
  pre_tasks:
    - name: Generate yaml manifest file
      ansible.builtin.template:
        dest: "{{ manifest_file }}"
        src: "{{ collection_path }}/config/generator_files/manifest.yaml.j2"

  roles:
    - ansible.content_builder.run