---
name: modules generator

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  # push:
  #   branches:
  #     - main
  #     - 'stable-*'
  # pull_request_target:
  #   types:
  #     - labeled
  #     - unlabeled
  #     - opened
  #     - reopened
  #     - synchronize
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      python_version: '3.9'
      ansible_version: 'stable-2.11'
      collection_path: "amazon_cloud"
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          path: ${{ env.collection_path }}

      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}

      - name: Install required ansible collections
        run: |
          ansible-galaxy collection install git+https://github.com/ansible-community/ansible.content_builder.git
          ansible-galaxy collection install ansible.utils
        shell: bash

      - name: Install python modules
        run: >-
          python3 -m pip install
          packaging
          q
          yq
          https://github.com/ansible/ansible/archive/${{ env.ansible_version }}.tar.gz
          -r /home/runner/.ansible/collections/ansible_collections/ansible/content_builder/requirements.txt
          --disable-pip-version-check
        shell: bash

      - name: Read current version from galaxy.yml
        id: read-version
        run: echo "current_version=$(yq -r .version galaxy.yml)" >> $GITHUB_OUTPUT
        shell: bash
        working-directory: ${{ env.collection_path }}

      - name: Compute next major release version
        id: compute-version
        run: 
          python -c "from packaging import version; v=version.Version('${{ steps.read-version.outputs.current_version }}'); print('next_version=%s.%s.%s' % (v.major, v.minor+1, v.micro))" >> $GITHUB_OUTPUT
        shell: bash

      - name: Generate collection modules
        run: >-
          ansible-playbook config/generator_files/build.yaml 
          -e collection_path="${{ github.workspace }}/${{ env.collection_path }}"
          -e collection_version="${{ steps.compute-version.outputs.next_version }}" -v
        shell: bash
        env:
          AWS_DEFAULT_REGION: "us-east-1"
        working-directory: ${{ env.collection_path }}
