---
name: modules generator

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  # push:
  #   branches:
  #     - main
  #     - 'stable-*'
  pull_request_target:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      python_version: '3.9'
      ansible_version: 'stable-2.11'
      collection_path: "amazon_cloud"
      ansible_path: "ansible"
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          path: ${{ env.collection_path }}

      - name: checkout ansible
        uses: actions/checkout@v3
        with:
          repository: ansible/ansible
          ref: stable-2.11
          path: ${{ env.ansible_path }}

      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}

      - name: Read current version from galaxy.yml
        id: read-version
        run: echo "current_version=$(yq -r .version galaxy.yml)" >> $GITHUB_OUTPUT
        shell: bash
        working-directory: ${{ env.collection_path }}

      - name: Compute next major release version
        id: compute-version
        run: |
          python3 -m pip install packaging
          python3 -c "from packaging import version; v=version.Version('${{ steps.read-version.outputs.current_version }}'); print('next_version=%s.%s.%s' % (v.major, v.minor+1, v.micro))" >> $GITHUB_OUTPUT
        shell: bash

      - name: Install required ansible collections
        run: |
          python3 -m pip install -r ${{ github.workspace }}/${{ env.ansible_path }}/requirements.txt
          source ${{ github.workspace }}/${{ env.ansible_path }}/hacking/env-setup
          ansible-galaxy collection install git+https://github.com/ansible-community/ansible.content_builder.git
          ansible-galaxy collection install ansible.utils
          python3 -m pip install -r /home/runner/.ansible/collections/ansible_collections/ansible/content_builder/requirements.txt
          ansible-playbook config/generator_files/build.yaml -e collection_path="${{ github.workspace }}/${{ env.collection_path }}" -e collection_version="${{ steps.compute-version.outputs.next_version }}" -v
        shell: bash
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ${{ env.collection_path }}
