---
name: Release

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  pull_request:
    types:
      - closed
    branches:
      - stable-*

jobs:
  tag:
    permissions:
      contents: write
      pull-requests: write
    uses: abikouo/gha_testing/blob/release_tag/.github/workflows/tag.yml@release_tag
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}